### ISSUE TITLE
🐞 `hit_dice` doesnt autocomplete and `hp` doesnt do anything

### ISSUE THREAD

**Issue by scottTomaszewski** [javalent/fantasy-statblocks#259]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

    ```statblock
    monster: Goblin
    hp: 100
    ```
would set the hp to `100`

Also, when I start to type `hit_dice` it would auto complete.  

Possibly need to document the relationship between the `hp` and `hit_dice` fields as well?

### Current behaviour

    ```statblock
    monster: Goblin
    hp: 100
    ```
does nothing and there is no autocomplete of `hit_dice`

### Reproduction

see statblock above

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.3.7 and 1.1.16

### Plugin Version

3.9.0

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This is an interesting interaction between hp, hit_dice, and the way Statblocks works internally.

`hit_dice` isn't a registered property of the layout, because its part of the property callback, so it will not be recommended for auto completion.

Additionally, the Goblin you are extending still has `hit_dice` defined in the base monster, so it is overriding the `hp` field.

You can turn it off directly:

````
```statblock
hit_dice:
hp: 100
creature: Goblin
```
````
