### ISSUE TITLE
Toggle to open Creature Pane without splitting the pane vertically

### ISSUE THREAD

**Issue by Pachtjuilaard** [javalent/fantasy-statblocks#342]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I'd expect the Open Creature Pane command to open the Creature Pane in a full size pane on the right, so I could bind a shortcut to that command to quickly check the current creature I'm using. Creating a toggle for this behaviour, or maybe an extra command (Open Creature Pane in new panel) would help. 

### Current behaviour

When using the command Open Creature Pane, the right panel always gets split vertically, showing the creature pane simultaneously with other stuff in the right panel. Using this command multiple times creates multiple splits, which makes the panels too small to be usable. 

### Reproduction

1. Use the 'Open Creature Pane' command.
2. Do it again. 
3. Do it again. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

3.17.0

### Confirmation

- [ ] I have disabled all other plugins and the issue still persists.

### Possible solution

A toggle or an extra command would be helpful, so people can choose to keep the current behaviour, or make the command always re-open the currently opened Creature Pane.

**Comment by natowb** [comment]
I've been working on this @Pachtjuilaard is this the functionality you are expecting
![image](https://github.com/javalent/fantasy-statblocks/assets/44450112/a7adac5e-5e64-4b8e-b165-6f18cdc1ad15)
![X888lXymzz](https://github.com/javalent/fantasy-statblocks/assets/44450112/ef025d0e-76ea-45e8-aa00-4307377f81cd)


@valentine195 ive got a solution for this working, however would you want there to be an option or should this just be standard behavior?

I ask because im not sure how usable this is.
![image](https://github.com/javalent/fantasy-statblocks/assets/44450112/7be9e964-1d89-4c82-84e9-4180c8ecebd9)
